version: '3.8'

services:
  webapp:
    build: .
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNET_HTTP_PORT=https://+:5001
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Elvis528
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro